### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Corcules** [alexanderweiss/nova-prettier#22] opened 2020-09-28 07:15 UTC
Seems to have an error on launch :

Extension encountered an uncaught exception:
/Users/maxibob/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/main.js (Line 330, Column 0)
SyntaxError: Unexpected token ';'. Expected ':' in ternary operator.

(last version of extension 1.5.1)

**Comment by alexanderweiss** [comment] 2020-09-28 07:36
Aha. What version of do you have installed?

**Comment by Corcules** [comment] 2020-09-28 07:53
Prettier 2.1.2

**Comment by alexanderweiss** [comment] 2020-09-28 08:08
Oh, sorry, part of my question was missing. I meant to ask what version of node. Prettier sounds good though. I might actually have to ask the people at Panic about this, because that code runs in Nova. So I would expect it to run the same for everyone, but apparently not...

**Comment by Corcules** [comment] 2020-09-28 08:15
Well i'm not very familiar with npm anyway...
npm version seems to be 4.0.2

**Comment by alexanderweiss** [comment] 2020-10-03 10:15
So, this appears to be caused by some macOS versions not supporting not supporting some newer JS syntax. I've just released v1.5.2 of the extension that should fix it. I wasn't able to test on older macOS yet though, so if you run into any other issue like this, let me know!

**Comment by Corcules** [comment] 2020-10-05 07:00
Hi Alexander, 

thank you for your efforts, trying the 1.5.2 this morning but have some other errors now (screen capture joined).
I'm running MacOS Mojave (not so old ?)

**Comment by alexanderweiss** [comment] 2020-10-05 08:15
I don't think attachments from an email get added? 😬

**Comment by Corcules** [comment] 2020-10-05 09:41
![Capture d’écran 2020-10-05 à 08 51 59](https://user-images.githubusercontent.com/24244917/95064199-ac2d2900-06ff-11eb-9270-b3f29876deb5.png)

**Comment by alexanderweiss** [comment] 2020-10-05 10:08
Ahhh. That's a stupid mistake. I'll let you know when I fix it. It won't work after I fix it though I'm afraid. It's actually trying to handle a different error here. But at least we'll find out the actual error.

Thanks a lot for helping with this!

**Comment by alexanderweiss** [comment] 2020-10-05 17:24
There's a new release out with a fix for this. Let me know what the actual error is :)

**Comment by Corcules** [comment] 2020-10-08 10:49
Have time to play with it today...
I have a new error when activate the extension, xcrun missing. Good to know, we have to install xcrun...
Come info here : https://apple.stackexchange.com/questions/321858/xcrun-missing-installing-xcode-command-line-tools-not-fixing-issue

After that, Prettier seems to load and start well, but...

**Closed** 2020-10-08 17:56 UTC
Labels: bug
